ALTER TABLE clicks ADD COLUMN os TEXT;
ALTER TABLE clicks ADD COLUMN browser TEXT;
ALTER TABLE clicks ADD COLUMN device TEXT;
ALTER TABLE clicks ADD COLUMN is_bot BOOLEAN DEFAULT FALSE;
ALTER TABLE clicks ADD COLUMN country TEXT;