ALTER TABLE clicks DROP COLUMN IF EXISTS country;
ALTER TABLE clicks DROP COLUMN IF EXISTS is_bot;
ALTER TABLE clicks DROP COLUMN IF EXISTS device;
ALTER TABLE clicks DROP COLUMN IF EXISTS browser;
ALTER TABLE clicks DROP COLUMN IF EXISTS os;